name: Kernel Compilation

on:
  push:
    branches:
      - native-postmarketos
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: false
        default: 'native-postmarketos'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Set up build environment
      run: |
        sudo apt update -y
        sudo apt install -y bc bison build-essential cpio flex gcc-aarch64-linux-gnu libelf-dev libncurses5-dev libssl-dev lld llvm clang python3 rsync

    - name: Compile Kernel
      run: |
        bash build_kernel.sh

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: KernelSU-Next-SM-A042F-native-postmarketos-${{ github.sha }}
        path: build/*.tar
        if-no-files-found: error
